kind: ConfigMap
apiVersion: v1
metadata:
  name: trino-configs
data:
  password-authenticator.properties: |
    password-authenticator.name=file
    file.password-file=/etc/trino/password.db
  group-mapping.properties: |
    admins:admin,jpaulraj
  group-provider.properties: |
    group-provider.name=file
    file.group-file=/etc/trino/group-mapping.properties
  jvm.config: >
    -server

    -agentpath:/usr/lib/trino/bin/libjvmkill.so

    -Xmx8G

    -XX:+UseG1GC

    -XX:G1HeapRegionSize=32M

    -XX:+ExplicitGCInvokesConcurrent

    -XX:+HeapDumpOnOutOfMemoryError

    -XX:+ExitOnOutOfMemoryError

    -XX:-OmitStackTraceInFastThrow

    -XX:ReservedCodeCacheSize=512M

    -XX:PerMethodRecompilationCutoff=10000

    -XX:PerBytecodeRecompilationCutoff=10000

    -Djdk.attach.allowAttachSelf=true

    -Djdk.nio.maxCachedBufferSize=2000000

    -XX:+UnlockDiagnosticVMOptions

    # Reduce starvation of threads by GClocker, recommend to set about the
    number of cpu cores (JDK-8192647)

    -XX:GCLockerRetryAllocationCount=32
  password.db: |-
    admin:$2y$10$bin5lxJLEZFfUeCMA1CWteHYj0oyrXQ3T4DcDGwhSKnRE1Kq7QZKC
    jpaulraj:$2y$10$4pCMKY9HIlMTuHKh5xu3Xu8osr3KHNMFSw8fI.wAshR2dkmrfmsu2
  log.properties: |
    io.trino=INFO
    io.trino.server.security.oauth2=DEBUG
    io.trino.server.ui.OAuth2WebUiAuthenticationFilter=DEBUG
  exchange-manager.properties: |
    exchange-manager.name=filesystem

    exchange.base-directories=/tmp/trino-local-file-system-exchange-manager
  node.properties: |
    node.environment=production
    node.data-dir=/data/trino
    plugin.dir=/usr/lib/trino/plugin
  config.properties: |-
    coordinator=true
    node-scheduler.include-coordinator=false 
    discovery-server.enabled=true
    discovery.uri=http://localhost:8080

    http-server.http.port=8080

    http-server.process-forwarded=true
    http-server.https.enabled=true
    http-server.https.port=8443
    
    http-server.https.keystore.path=/etc/trino/keystore/keystore.jks
    http-server.https.keystore.path=/etc/trino/keystore-p12/trino.p12
    http-server.https.keystore.key=redhat2024

    http-server.authentication.oauth2.oidc.discovery=true
    web-ui.authentication.type=oauth2
    http-server.authentication.allow-insecure-over-http=true
    http-server.authentication.oauth2.issuer=${ENV:OIDC_ISSUER}
    http-server.authentication.oauth2.client-id=${ENV:CLIENT_ID}
    http-server.authentication.oauth2.client-secret=${ENV:TRINO_OAUTH_SECRET}
    http-server.authentication.oauth2.scopes=openid

    http-server.authentication.oauth2.oidc.use-userinfo-endpoint=true
    http-server.authentication.oauth2.auth-url=${ENV:OAUTH_AUTHORIZE_URL}
    http-server.authentication.oauth2.token-url=${ENV:OAUTH_TOKEN_URL}
    http-server.authentication.oauth2.jwks-url=${ENV:JWKS_URI}
    http-server.authentication.oauth2.userinfo-url=${ENV:OAUTH_USER_INFO}