kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: redis
  labels:
    app.kubernetes.io/part-of: superset
spec:
  replicas: 1
  selector:
    name: redis
  template:
    metadata:
      labels:
        name: redis
    spec:
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis
      containers:
        - resources:
            limits:
              memory: 512Mi
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - '-i'
                - '-c'
                - >-
                  test "$(redis-cli -h 127.0.0.1 -a $REDIS_PASSWORD ping)" ==
                  "PONG"
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          name: redis
          livenessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 30
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis
                  key: database-password
          securityContext:
            capabilities: {}
            privileged: false
          ports:
            - containerPort: 6379
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - name: redis-data
              mountPath: /var/lib/redis/data
          terminationMessagePolicy: File
          # image: redis:7.2.4
          image: 'quay.io/osclimate/redis:7.2.4'
      restartPolicy: Always
      securityContext: {}