---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: datamesh-demo-common-apps
  namespace: openshift-gitops
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
spec:
  destination:
    namespace: datamesh-demo
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    repoURL: https://github.com/opendatahub-io-contrib/datamesh-platform.git
    path: deployment/common/kustomize/overlays/development
    targetRevision: argocd
    # plugin:
    #   name: argocd-vault-plugin-kustomize
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=true
    - ServerSideApply=true
  dependencies:
    - name: datamesh-demo-namespace-apps
      namespace: openshift-gitops