apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
generatorOptions:
 disableNameSuffixHash: true
secretGenerator:
- name: default-pull-secret
  files:
    - ./deployment-manifest/config.json

resources:

#  - ./deployment-manifest/default-pull-secret.yaml
 - ./deployment-manifest/service-account-default.yaml
 - ./deployment-manifest/service-account-trino.yaml
 - ./deployment-manifest/service-account-superset.yaml
 - ./deployment-manifest/scc-custom-anyuser.yaml
 - ./deployment-manifest/scc-rolebinding-superset.yaml
 - ./deployment-manifest/scc-rolebinding-trino.yaml
# patches:
# - target:
#     version: security.openshift.io/v1
#     kind: SecurityContextConstraints
#     name: scc-custom-anyuser
#   patch: |-
#     - op: add
#       path: users
#       value: "- system:serviceaccount::trino-default"
# - target:
#     version: security.openshift.io/v1
#     kind: SecurityContextConstraints
#     name: scc-custom-anyuser
#   patch: |-
#     - op: add
#       path: users
#       value: "- system:serviceaccount::superset-serviceaccount"
# patches:
# - target:
#     group: rbac.authorization.k8s.io
#     version: v1
#     kind: ClusterRole
#     name: system:image-builder
#   patch: |-
#     - op: add
#       path: /rules/0/resources/0
#       value: "secrets"
# - target:
#     group: ""
#     version: v1
#     kind: ServiceAccount
#     name: default
#   patch: |-
#     - op: add
#       path: /imagePullSecrets/-
#       value:
#         name: default-pull-secret