apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: datamesh-anyuid-scc-binding-trino
  # namespace: example
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:scc-custom-anyuser
subjects:
- kind: ServiceAccount
  name: trino-default
  # namespace: example
