apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

secretGenerator:
  - name: keystore-p12
    type: Opaque
    files:
      - ./deployment-manifest/keystores/trino.p12
  - name: keystore
    type: Opaque
    files:
      - ./deployment-manifest/keystores/keystore.jks

resources:
- ./deployment-manifest/hive/secret.yaml
- ./deployment-manifest/hive/deployment-potgress.yaml
- ./deployment-manifest/hive/service-hive-postgres.yaml

- ./deployment-manifest/hive/deployment-hivemetastore.yaml
- ./deployment-manifest/hive/service-hivemetastore.yaml
# sso
# - ./deployment-manifest/ssc-trino-custom.yaml
- ./deployment-manifest/sso/service-account-trino.yaml
- ./deployment-manifest/sso/secret-trino-coordoinator.yaml
# - ./deployment-manifest/sso/secret-trino-ssl-keystore-p12.yaml
# - ./deployment-manifest/sso/secret-trino-ssl-keystore.yaml
- ./deployment-manifest/sso/configmap-schema-coordinator.yaml
- ./deployment-manifest/sso/configmap-schema-worker.yaml
- ./deployment-manifest/sso/configmap-trino-catalog.yaml

- ./deployment-manifest/sso/configmap-trino-coordinator.yaml
- ./deployment-manifest/sso/configmap-trino-worker.yaml

- ./deployment-manifest/sso/deployment-trino-coordinator.yaml
- ./deployment-manifest/sso/deployment-trino-worker.yaml
- ./deployment-manifest/sso/service-trino-coordinator.yaml
- ./deployment-manifest/sso/route-trino-coordinator.yaml